global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['ca-adpq-prototype.eastus2.cloudapp.azure.com:9090']
        labels:
          group: 'prometheus'

      - targets: ['ca-adpq-prototype.eastus2.cloudapp.azure.com:9100','ca-adpq-prototype.eastus2.cloudapp.azure.com:9103']
        labels:
          group: 'system'

      - targets: ['ca-adpq-prototype.eastus2.cloudapp.azure.com:9104']
        labels:
          group: 'mysql'

      - targets: ['ca-adpq-prototype.eastus2.cloudapp.azure.com:9102']
        labels:
          group: 'containers'