version: '{build}'
pull_requests:
  do_not_increment_build_number: true
nuget:
  disable_publish_on_pr: true
test: off
environment:
  access_token:
    secure: HjU3pyqQhmk1oDXDTBY4iwPi95AOpIIBea2/D4cXRUVi5No7e/In7rjgMZqM6SZX
  git_email:
    secure: oRZ8Osh1fASFzE/ff8aFltjftBtlRP422CKRxGSfIVA=

branches:
  only:
  - develop
build_script:
 - ps: .\build_aspdotnet_core.ps1
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "$($env:git_email)"
  - git config --global user.name "Ryan Chadwick"
  - git config --global core.autocrlf true
  - git checkout develop
  - git add .
  - git commit -m "ci build"
  - git status
  - git push origin develop:release -f
  
branches:
  only:
  - latest/web/b
build_script:
 - ps: .\build_aspdotnet_core.ps1
on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "$($env:git_email)"
  - git config --global user.name "Ryan Chadwick"
  - git config --global core.autocrlf true
  - git checkout latest/web/b
  - git add .
  - git commit -m "CI build for Web"
  - git status
  - git push origin latest/web/b:latest/web/r -f
